# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTIBILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.

bl_info = {
    "name" : "Connectome→Blender",
    "author" : "jellocube",
    "description" : "Import connectome tracts generated by DSI Studio and convert them to Blender curves and compound meshes.",
    "blender" : (2, 80, 0),
    "version" : (0, 0, 3),
    "location" : "View3D",
    "warning" : "",
    "category" : "Import"
}

import bpy
from bpy.props import *     # Additional Blender operation Properties
from bpy_extras.io_utils import ImportHelper

from . c2b_plot_tracts import *
from . c2b_parser import *
from . c2b_panel import *

bpy.types.Scene.tract_file = StringProperty(name="Tract source file", 
               description="Location of the tract source file in UTF-8 plaintext format")

class Importer(bpy.types.Operator, ImportHelper):
    bl_idname = "c2b.import"
    bl_label = "import tracts"

    filename_ext = ".txt"

    filter_glob: StringProperty(
        default="*.txt",
        maxlen=255
    )

    def execute(self, context: bpy.types.Context):
        print("importing file:", self.filepath)
        context.scene["tract_file"] = self.filepath
        bpy.ops.c2b.parse() # trigger parser

        return {'FINISHED'}

classes = [PlotTracts, Parser, Panel, Importer]

register, unregister = bpy.utils.register_classes_factory(classes)
