# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTIBILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.

bl_info = {
    "name" : "Brain in a Blender",
    "author" : "jellocube",
    "description" : "Import connectome tracts generated by DSI Studio and convert them to Blender curves and compound meshes.",
    "blender" : (2, 80, 0),
    "version" : (0, 0, 1),
    "location" : "View3D",
    "warning" : "",
    "category" : "Generic"
}

import bpy
from bpy.props import *     #   Additional Blender operation Properties

from . biab_plot_tracts import *
from . biab_center_cursor import Biab_CenterCursor
from . biab_panel import Biab_Panel

bpy.types.Scene.tract_file = StringProperty(name="Tract source file", 
               subtype="FILE_PATH", 
               description="Location of the tract source file in UTF-8 plaintext format")

classes = (Biab_PlotTracts, Biab_CenterCursor, Biab_Panel)

register, unregister = bpy.utils.register_classes_factory(classes)