# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTIBILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.

bl_info = {
    "name" : "Connectome→Blender",
    "author" : "jellocube",
    "description" : "Import connectome tracts generated by DSI Studio and convert them to Blender curves and compound meshes.",
    "blender" : (2, 80, 0),
    "version" : (0, 0, 3),
    "location" : "View3D",
    "warning" : "",
    "category" : "Generic"
}

import bpy
from bpy.props import *     # Additional Blender operation Properties

from . c2b_plot_tracts import *
from . c2b_parser import *
from . c2b_panel import *

bpy.types.Scene.tract_file = StringProperty(name="Tract source file", 
               subtype="FILE_PATH", 
               description="Location of the tract source file in UTF-8 plaintext format")

bpy.types.Scene.tract_count = IntProperty(name="Tract count", 
               subtype="UNSIGNED", 
               description="The total count of all tract groups.")

bpy.types.Scene.curve_count = IntProperty(name="Curve count", 
               subtype="UNSIGNED", 
               description="The total count of all curves in respective tracts.")

bpy.types.Scene.vertex_count = IntProperty(name="Vertex count", 
               subtype="UNSIGNED", 
               description="The total count of all vertices in all tracts.")

classes = (PlotTracts, Parser, Panel)

register, unregister = bpy.utils.register_classes_factory(classes)